# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2030f1d33eabba3ce37e5eb026fe6834a9c8f03754fbe00389094402c14ff7a1e0b5efc4c3cb122d74ff1251ec4c30c1252021a24945b2ab40ac0614db8924f

test:
  secret_key_base: 5f1acf3c4fb11364a96537db789a2337a428788a3f0e30fd175996e9e1003c649e009b9a926c4cdd30c746213c1170968053af593e2d003ae463c1671d14936d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
